const os = require('node:os')
const { ConvertTo, MB } = require('./KB_MB_GB')
console.log('Arquitectura', os.arch())
console.log('CPUs', os.cpus())
console.log('-------------------')
console.log('nombre del SO', os.platform())
console.log('version del SO', os.release())
console.log('Memoria total', os.totalmem())
console.log('-------------------')
const totalmem = os.totalmem()
console.log(ConvertTo('Total (KB)', totalmem, 1024))
console.log(ConvertTo('Total (MB)', totalmem, MB))
console.log(ConvertTo('Total (GB)', totalmem, (2 ** 30)))
const FREE_MEMORY = os.freemem()
console.log('-------------------')
console.log(os.freemem())
console.log(ConvertTo('libre (KB)', FREE_MEMORY, 1024))
console.log(ConvertTo('libre (MB)', FREE_MEMORY, 1048576))
console.log(ConvertTo('libre (GB)', FREE_MEMORY, (1073741824)))
